### ISSUE TITLE
Shared Playlists Not Displayed in Playlists Chart

### ISSUE THREAD

**Issue by alichtman** [Rigellute/spotify-tui#3] opened 2019-09-17 22:58 UTC

**Comment by Rigellute** [comment] 2019-09-18 08:09
Good point. 

Implementation notes for my own benefit:

1. Fetch the current user to get `user_id` (perhaps display this information in the "home" block?)
1. Add the `playlist-read-collaborative` scope
1. Use `user_playlists` method ([example](https://github.com/ramsayleung/rspotify/blob/7c61a1e27bc9fb9ba680d66eb610a06c6f1a430b/examples/user_playlists.rs))

**Comment by sputnick1124** [comment] 2019-10-26 01:44
I am unable to reproduce this. My collaborative playlists appear alongside all of my private ones already somehow.

That said, I don't think it's necessary to get the user ID and make a call to `user_playlists`. According to [the API reference](https://developer.spotify.com/documentation/web-api/reference/playlists/get-a-list-of-current-users-playlists/), simply adding the `playlist-read-collaborative` scope should be sufficient to get the collaborative lists, correct?

**Comment by sputnick1124** [comment] 2019-10-27 00:45
I managed to reproduce after making one of my private playlists collaborative and then resetting my client secret key and re-registering the spotify-tui client a few times. After a few resets/restarts, the playlist stopped showing up in my `Playlists` list.

I can confirm that simply adding the `playlist-read-collaborative` scope to `SCOPES` has the desired effect of returning all playlists.

I have it working in [my branch](https://github.com/sputnick1124/spotify-tui/tree/3-shared-playlists) and will submit a pull request shortly.

I would like to get some more people testing it to ensure that this works properly across a variety of configs.

**Comment by Rigellute** [comment] 2019-10-27 09:15
#115 Should close this issue

**Closed by Rigellute** 2019-10-27 09:15 UTC
Labels: good first issue
