### ISSUE TITLE
Playlist sorting

### ISSUE THREAD

**Issue by csonyi** [Rigellute/spotify-tui#529] opened 2020-07-15 09:28 UTC
I might have missed it in the help menu, even though i looked through it like 3 times...
It would be awesome if we could have the ability to sort the current list by artist/title/album/etc...

**Comment by Rigellute** [comment] 2020-07-22 09:24
This would be a great feature however I can't see a way to do this via the Spotify API.

I'd like to avoid a homegrown fix such as fetching all items in a playlist, then sorting client side.

**Comment by realmain** [comment] 2020-07-22 23:30
I don't believe there is a way to do this via API, it has to be done client side.

I personally do find this a great feature though! If someone can make a clean pull request for this, it'd be amazing!

**Comment by sputnick1124** [comment] 2020-09-29 03:51
I think this is a duplicate of #76, no?

**Comment by Rigellute** [comment] 2020-09-30 17:13
Closing in favour of #76 (thanks for pointing out @sputnick1124)

**Closed by Rigellute** 2020-09-30 17:13 UTC
