### ISSUE TITLE
Interface is slow

### ISSUE THREAD

**Issue by steakknife** [Rigellute/spotify-tui#24] opened 2019-10-08 11:29 UTC
Scrolling should be asynchronous and fast, or spt defeats its own utility.

**Comment by Rigellute** [comment] 2019-10-08 19:15
Are you able to share more about what is slow?

At the moment, no real optimizations are in place - the full UI renders on every tick. So it's possible that things get slow on some systems.

That said, it's likely that the terminal emulator you're using is the bottleneck. Which terminal are you using?

I recommend `kitty` or `alacritty`.

**Comment by ericonr** [comment] 2019-10-11 13:42
I've had the same issue, and I'm using spt through tmux on alacritty. I believe in my case the problem is mostly related to internet issues, because, when I'm on a stable connection, it's pretty snappy overall. When I am on a slow connection (which is, however, fast enough to stream music through spotifyd), it really lags. It happens with pretty much every part of the interface, such as navigating the music choice view and changing to the device selection view (in this case it even takes a long while to even get to the device selection view).

**Comment by Rigellute** [comment] 2019-10-11 13:56
Ah interesting, thanks for this added info.

**Comment by Windexi** [comment] 2019-10-21 12:40
a little late, but agreed, the problem is exactly with slow connections. been happening for me as well.

**Comment by Rigellute** [comment] 2019-10-21 13:53
Cool - I suspect that the polling for current playback every 5 seconds might be slowing things down.

A good fix would be to do all the network requests in another thread - right now they are sychronous. 

I will investigate this!

**Comment by atidyshirt** [comment] 2019-10-28 11:48
After some testing I have found that my interface is very slow (almost unusable) at launch until I select the first song, after that if seems to operate well. This could be a problem on my end however, would like to know if anyone else is facing a similar problem.

**Comment by robatipoor** [comment] 2019-12-20 08:14
i have same problem interface is very slow (almost unusable)

**Comment by Rigellute** [comment] 2020-03-12 10:50
Should be fixed in 0.16.0

**Closed by Rigellute** 2020-03-12 10:50 UTC
