### ISSUE TITLE
400 Only Valid Bearer Authentication Supported

### ISSUE THREAD

**Issue by sputnick1124** [Rigellute/spotify-tui#410] opened 2020-04-22 12:17 UTC
Occasionally (usually after `spt` has been running for some time), playback will be frozen and any action will result in a "400 Only Valid Bearer Authentication Supported" error from the API.

Wondering if we can handle 400's with a re-auth routine or something similar. If we need better/more granular errors from `rspotify`, I am working on putting together a PR to address [better error descriptions](https://github.com/ramsayleung/rspotify/issues/63) and can work something out there.

**Comment by Rigellute** [comment] 2020-04-22 14:36
We currently try to perform reauth when the token has expired ([here](https://github.com/Rigellute/spotify-tui/blob/master/src/main.rs#L303)). Perhaps this isn't working properly anymore?

Having more granular errors from `rspotify` would be great actually, thanks for looking into that!

**Comment by TimotheeGerber** [comment] 2020-04-25 17:00
I have the same issue. Re-authentication is not working correctly all the time. I checked the code and I think I found the problem.

Re-authentication is done when `Instant::now() > app.spotify_token_expiry`. These expiration date is computed [here](https://github.com/Rigellute/spotify-tui/blob/4f0c516791be95a85fb29bcf8325eee9672cc86e/src/network.rs#L79), with the current time + token lifetime (`expires_in`). The problem is that the current time is not the time the token started to be valid when we are using a cached version of the token. As a consequence, it happens that the expiration date is too far in the future to trigger re-authentication.

To solve this problem, the expiration date should be computed from the `expires_at` field. Unfortunately, it seems there is no `from_timestamp` function in `std::time`. I don't want to add another dependency just for that. I will try something and propose a PR if it works.

**Comment by TimotheeGerber** [comment] 2020-04-25 17:57
I found a way to mimic a `from_timestamp` function in Rust. I put it here in case someone is interested:

```rust
use std::time::{Duration, SystemTime};
let time = SystemTime::UNIX_EPOCH + Duration::from_secs(timestamp);
```
I used this on the `expires_at` token field to propose the fix for this issue.

**Closed** 2020-04-27 15:42 UTC
