### ISSUE TITLE
Is it possible to sort Albums or Artists alphabetically

### ISSUE THREAD

**Issue by Godridge** [Rigellute/spotify-tui#340] opened 2020-03-16 16:31 UTC

**Comment by BKitor** [comment] 2020-03-16 18:59
Related: #76

**Comment by Rigellute** [comment] 2020-03-17 13:37
Not currently possible in `spotify-tui`, it doesn't look like the Spotify API lets us sort from their end. We could sort the results _after_ we receive them, but not sure how useful this is?

Will close this as it's a duplicate of #76

**Closed by Rigellute** 2020-03-17 13:37 UTC

**Comment by Godridge** [comment] 2020-03-17 13:56
How useful is the artists tab at all when it's sorted by when they were added?  I'll help you out; its absolutely fucking useless.  By your logic, remove the artists tab altogether because it's non-functional.  How useful would it be to sort albums by artist?  Much more useful than leaving the results a jumbled mess.  If you can't retrieve all the results at once and sort them in a sane manner, delete the artists tab

**Comment by Rigellute** [comment] 2020-03-17 15:19
Caching saved albums could be a good solution.

Sorry to hear you find the artists view absolutely useless 😞
