### ISSUE TITLE
no device is found

### ISSUE THREAD

**Issue by verajosemanuel** [Rigellute/spotify-tui#310] opened 2020-02-24 11:43 UTC
installed spotifyd and spt.
run spotifyd

```
 ps -ef | grep spotify
jose     11868     1  0 12:40 ?        00:00:00 spotifyd
jose     11885 11656  0 12:40 pts/4    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn spotify
```
run spt (installed via snap)

![2020-02-24_12-42](https://user-images.githubusercontent.com/15836677/75149862-43aab200-5703-11ea-9690-b97bc5feac58.png)

**Comment by Rigellute** [comment] 2020-02-24 18:23
Could be that you've logged in to a different account using spotifyd compared to the account used to create the client credientials for spotify-tui?

**Comment by verajosemanuel** [comment] 2020-02-24 18:37
Nop

**Comment by er0k** [comment] 2020-02-25 14:58
I have the same issue on debian buster

```
$ uname -srv
Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26)

$ spotifyd --version
spotifyd 0.2.24

$ spt --version
spotify-tui 0.15.0
```

I get "No devices found" in spotify-tui. 

However, if I start spotifyd and then use the Spotify client on my phone, the spotifyd device shows in the Android client. Once I switch to the spotifyd device with the Android client, the spotifyd device appears in spotify-tui and I can use it normally. So, it seems like there may be an issue with autodiscovery between spotifyd and spotify-tui?

**Comment by Rigellute** [comment] 2020-02-25 15:26
Hmm... spotify-tui calls the [`devices` endpoint](https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/) from the spotify api and displays that list.

Is it possible that the spotifyd client is not active when spotify-tui goes to this devices screen? We could implement some polling on that endpoint (currently the request is only made when that screen is first shown).

**Comment by ZurMaD** [comment] 2020-02-25 20:45
Same error in Windows 10

![image](https://user-images.githubusercontent.com/28235457/75286055-cc9a1a00-57e5-11ea-88d3-77482b06865a.png)
Latest version by now

**Comment by ZurMaD** [comment] 2020-02-25 20:46
c

> Same error in Windows 10
> 
> ![image](https://user-images.githubusercontent.com/28235457/75286055-cc9a1a00-57e5-11ea-88d3-77482b06865a.png)
> Latest version by now

Oh, I see. Spotify TUI needs Spotify installed?

**Comment by Spinnerthing** [comment] 2020-02-25 21:31
I wonder if the issue is related to spotifyd, I have been having issues with spotifyd not being viewable as a device with either the spotify web client or spt, but if I use the official spotify client on linux it can see spotifyd device and once that has seen it then spotifyd is visible to both the web client and spt.

**Comment by ZurMaD** [comment] 2020-02-25 22:08
You need a spotify client open, maybe your phone, TV or other device.

**Comment by Spinnerthing** [comment] 2020-02-25 22:57
Actually for me it was a fail regarding config for spotifyd, it was in discovery mode because the username/password was not set. (Because it was not reading the conf file where I'd put it)

**Comment by Spinnerthing** [comment] 2020-02-26 10:06
@er0k your issue sounds like a config fail in spotifyd, when it doesn't have a valid username/password then it has a discovery mode which needs an official client to make it then become discoverable to spotify tui and even the web client.

**Comment by nachocarballeda** [comment] 2020-03-23 15:20
> You need a spotify client open, maybe your phone, TV or other device. Premium is necessary.

I solve the same issue with this reply   :¬|

**Comment by Rigellute** [comment] 2020-03-30 09:29
Closing as @ZurMaD and @nachocarballeda are correct. Premium is necessary to control playback

**Closed by Rigellute** 2020-03-30 09:29 UTC

**Comment by breuerfelix** [comment] 2020-05-01 09:30
same issue here.  
i have the spotifyd daemon run at startup as a system service.

when i start spotify tui right after system start it is able to detect the device. if i wanna hear music some hours later it is not able to detect my spotifyd again even though it is running fine. i can start listening on that via smartphone. AFTER i hit start on the smartphone it shows up when pressing d again on spotify tui.

Seems like some idling problem to me. any advices ?

**Comment by datkush420** [comment] 2020-05-04 22:53
I'm having the same issue as outlined above by @breuerfelix. The devices menu "d" is empty. If I open spotify on my phone and select my computer, go back to terminal and hit "d" again, the list populates and I can play music.

**Comment by breuerfelix** [comment] 2020-05-05 14:01
@Rigellute maybe reopen this issue again ? :)

**Comment by Spinnerthing** [comment] 2020-05-06 06:30
@breuerfelix I don't think these are issues with spotify-tui but spotifyd, @datkush420 issue sounds more like a config issue with spotifyd going in to discovery mode.

For you @breuerfelix maybe try open a bug report with spotifyd about it not being discoverable after a while of inactivity. When I had my issues I found a similar sort of problem was being discussed there too.

**Comment by breuerfelix** [comment] 2020-05-06 10:07
@Spinnerthing i don't think the problem is spotifyd not being discoverable.  
My Smartphone (fresh start or start from idle) is doing really fine with discovering the client on my computer :)

**Comment by Spinnerthing** [comment] 2020-05-06 19:21
@breuerfelix interesting to hear, maybe post a new bug report with that all of that relevant information if you can't find another bug relating to it?
This issue people experienced in this bug report, me included, before was not a bug.

**Comment by datkush420** [comment] 2020-05-07 22:49
I can open the official Spotify client on any device (tablets, phones, laptops, android, ios, mac, windows, linux, etc.) and immediately see spotifyd named "rhArchLinux". Spotify-tui is the only client that can't see it. I don't see how this is an issue with spotifyd when spotify-tui is the only client having trouble seeing it.

**Comment by Spinnerthing** [comment] 2020-05-08 15:39
@datkush420 I am glad to hear it's resolved. The discovery mode of spotifyd does easily cause confusion with spotify-tui.

**Comment by marcelbuesing** [comment] 2020-06-14 20:42
Quote from spotify API docs:

Connect Web API relies on local network connections to discover and interact with some devices.

For example, when:

- A new device is added to the network
- A device is in “sleep” mode
- A device on the local network is currently tied to another user account, or
- Other reasons specific to the device

As a result, some devices that appear in the Connect picker within the Spotify application may not always be visible or available on the Connect Web API Endpoints.

https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/

Is there some way to programmatically do the same as the Spotify clients do for network device discovery, I assume it's something related to mdns?

**Comment by UdittLamba** [comment] 2021-05-17 05:15
> You need a spotify client open, maybe your phone, TV or other device. Premium is necessary.

that's what spotifyd is for...

**Comment by dxtr85** [comment] 2022-04-21 05:25
I have both daemon and spotify-tui built from source.
TUI does not detect daemon, I can not even connect from my phone (daemon is seen from my phone).

dxtr@W540:~/projects/spotifyd$ ./target/release/spotifyd --version
spotifyd 0.3.3
dxtr@W540:~/projects/spotifyd$ ../spotify-tui/target/release/spt --version
spotify-tui 0.25.0

**Comment by TornaxO7** [comment] 2022-07-03 10:38
> You need a spotify client open, maybe your phone, TV or other device. Premium is necessary.

This should be added to the README in my opinion or I was just blind.

Anyways, is it possible to hear music without having the spotify-client running?

**Comment by mirachh** [comment] 2024-01-26 08:01
Same problem. Any solution?

**Comment by TornaxO7** [comment] 2024-01-26 08:23
@mirachh I highly recommend [spotify-player](https://github.com/aome510/spotify-player) since it's easier to setup and actively maintained.

**Comment by mirachh** [comment] 2024-01-26 08:34
Thanks...

**Comment by jaketae** [comment] 2024-01-30 01:15
Here's something that worked for me on macOS.

1. Install `spotifyd` and `spotify-tui`
2. Set up `spotifyd` ([documentation](https://docs.spotifyd.rs/config/File.html))
3. Start `spotifyd` via `brew services start spotifyd`
4. Run `spt`; `spotifyd` should now show up as an available device
